config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post 'user_token' => 'user_token#create'
  devise_for :users
  root to: 'pages#home'

  # --- Create
  get '/spots/new', to: 'spots#new', as: :new_spot
  post '/spots', to: 'spots#create'

  # --- Read
  get '/spots', to: 'spots#index'
  get '/spots/:id', to: 'spots#show', as: :spot

  # --- Edit
  get '/spots/:id/edit', to: 'spots#edit', as: :edit_spot
  patch '/spots/:id', to: 'spots#update'

  # --- Delete
  delete '/spots/:id', to: 'spots#destroy', as: :destroy

  # --- Posts
  post '/spots/:spot_id/posts', to: 'posts#create', as: :spot_posts

  # --- Api
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :update, :create ] do
        collection do
          post 'favorites'
        end
        collection do
          get 'profile'
        end
      end
      resources :spots, only: [ :index, :show, :update, :create, :destroy ] do
        collection do
          get 'favorites'
        end
        resources :posts, only: [:index, :create]
      end
    end
  end

end

app/models/spot.rb
class Spot < ApplicationRecord
  # acts_as_token_authenticatable

  belongs_to :user
  has_many :checkins, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :spot_contents, dependent: :destroy
  has_many :posts, dependent: :destroy
  # has_many :post_contents, through: :post
  validates_presence_of :default_image, :message => "You must upload an image!"
  # validates_inclusion_of :spot_rating, :in => 1..5, :message => "must be between 1 and 5"
  validates_inclusion_of :difficulty_rating, :in => 1..10, :message => "must be between 1 and 10"


  mount_uploader :default_image, PhotoUploader
  # attr_accessor :default_image

  include PgSearch

  pg_search_scope :search_by_type,
    against: [ :spot_type ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/api/v1/spots_controller.rb
class Api::V1::SpotsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, except: [:index, :favorites]
  acts_as_token_authentication_handler_for Spot, except: [:index, :create, :favorites]
  # protect_from_forgery with: :exception
  protect_from_forgery prepend: true
  # skip_before_action :verify_authenticity_token
  respond_to :json

  def index
    @spots = Spot.all
    # .sort((a, b) => (a.spot_type > b.spot_type) ? 1 : ((b.spot_type > a.spot_type) ? -1 : 0))
    @all_spots = {}

    Spot.distinct.pluck(:spot_type).each do |type|
      @all_spots[type] = Spot.where(:spot_type => type).order(created_at: :desc)
    end

    render json: @all_spots.to_json(:include => :user)
  end

  def create
    p "Starting--------------"
    @spot = Spot.new(set_params)
    p params[:default_image]
    @spot.default_image = 'http://lc-j4J9R8FV.cn-n1.lcfile.com/88c88f5dd8ca2d79a41c'
    @spot.remote_default_image_url = params[:remote_default_image_url]
    p @spot.default_image
    # @spot.default_image = @spot.default_image.gsub('http://', 'https://')
    p "Starting--------------"
    if @spot.save
      p "SUCESS---------------------------------"
      render json: @spot if @spot.persisted?
      p @spot
    else
      render_error
    end
  end

  def favorites
    fav_count = Favorite.where(spot_id: params[:spotId]).count
    render json: { favCount: fav_count }
  end

  def render_error
    render json: { errors: @spot.errors.full_messages },
           status: :unprocessable_entity
  end

  def set_params
    params.require(:spot).permit(:name, :avatar_url, :gender, :province, :city, :spot_rating,
                                 :difficulty_rating, :spot_type, :default_image, :user_id,
                                 :geo_lat, :geo_lng, :address, :authentication_token, :remote_default_image_url)
  end
end

app/controllers/spot_controller.rb
class SpotsController < ApplicationController
    
    # -- Read
    def index
        @spots = Spot.all
    end

    def show
    end

    private

    def load
        @spot = Spot.find(params[:id])
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
    before_action :load, only: [:show, :update, :edit, :destroy]
    # acts_as_token_authentication_handler_for User, except: [:index, :new, :create,]
    # --- Create

    def new
        @spot = current_user.spots.new
        authorize @spot
    end

    def create
      @spot = current_user.spots.new(spot_params)
      @spot.spot_type = type(@spot.spot_type)

      authorize @spot

      if @spot.save
        redirect_to spot_path(@spot)
      else
        render 'new'
      end
    end

    # --- Read

    def index
      @allSpots = policy_scope(Spot).order(created_at: :desc)

      if params[:query].present?
         sql_query = "spot_type ILIKE :query"
        @spots = policy_scope(Spot).where(sql_query, query: "%#{params[:query]}%").order(created_at: :desc)
      else
        @spots = policy_scope(Spot).order(created_at: :desc)
      end

      @markers = @spots.map do |spot|
        {
          lat: spot.geo_lat,
          lng: spot.geo_lng,

          infoWindow: { content: render_to_string(partial: "/spots/map_window", locals: { spot: spot }) },
          image_url: helpers.asset_url('https://www.topdraw.com/assets/uploads/2016/05/66255487_thumbnail-591x640.png')
        }
      end
    end

    def show
      @post = Post.new
      @posts = Post.where(spot_id: params[:id])
      @content = PostContent.new
    end

    # --- Update

    def edit
    end

    def update
        @spot.update(spot_params)
        redirect_to '/spots'
    end

    def destroy
        @spot.destroy
        redirect_to '/spots'
    end

    private

    def load
        @spot = Spot.find(params[:id])
        authorize @spot
    end

    def spot_params
        params.require(:spot).permit(:spot_type, :difficulty_rating, :default_image, :geo_lng, :geo_lat, :query, :address, :authenticity_token)
    end

    def type(num)
      types = {
      '0' => "Ledge",
      '1' => "Rail",
      '2' => "Stair set",
      '3' => "Park",
      '4' => "Transition",
      '5' => "Manual pad"
      }
      types[num]
    end
end

app/views/spots/_map_window.html.erb
<div class="map-popup">
  <%= cl_image_tag(spot.default_image, :crop => :fill) %>
  <div class="map-popup-infos">
    <h2><%= spot.spot_type %></h2>
    <p><%= spot.address %></p>
  </div>
</div>
<!--
<h3><%= spot.spot_type %></h3>
<p><%= spot.address %></p>
<p><%= spot.spot_type %></p> -->

app/views/spots/edit.html.erb
<h3>Edit a spot</h3>
<%= simple_form_for(@spot) do |f| %>
     <%= f.input :spot_rating %>
     <%= f.input :difficulty_rating %>
     <%= f.input :default_image %>
     <%= f.input :default_image_cache, as: :hidden %>
     <%= f.button :submit %>
<% end %>

app/views/spots/index.html.erb
<div class="Container">
  <div class="Content">
    <div class="Wrapper">
      <div class="RightContent" id="map" data-view-type="spots" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class="LeftContent">
        <% @spots.each do |spot| %>
         <%= render 'shared/big-card',  :spot => spot %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spots/new.html.erb
<% types = {
    0 => "Ledge",
    1 => "Rail",
    2 => "Stair set",
    3 => "Park",
    4 => "Transition",
    5 => "Manual pad"
}
%>

<div style="margin: 3rem auto; width: 50%; box-shadow:3px 3px 5px 6px #ccc; border-radius: 10px; padding: 20px; background-color: white;">

    <h3>Add a spot</h3>
    <%= simple_form_for(@spot) do |f| %>
        <%= f.input :spot_type, :collection => types.sort.map { |k,v| [v,k]}  %>
        <%= f.input :difficulty_rating %>
        <%= f.input :default_image, label: false, class: "btn btn-outline-dark" %>
        <%= f.input :default_image_cache, as: :hidden %>

        <div
          id="map"
          style="width: 100%;
          height: 200px;"
          data-view-type="create_spot"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

        <%= f.input :address, as: :text, :input_html => { :id => 'flat_address' } %>


        <%= f.input :geo_lat, as: :hidden, class: "geo-lat" %>
        <%= f.input :geo_lng, as: :hidden, class: "geo-lng" %>

        <pre id='coordinates' class='coordinates'></pre>
        <br>
        <%= f.button :submit, class: "btn btn-primary"%>
    <% end %>



</div>

app/views/spots/show.html.erb
<div class="container" style="width: 100%;">
  <div class="row" style="margin: 0 auto; width: 100%; padding: 0;">

    <div class="col-sm carousel slide" id="carouselExampleInterval" class="carousel slide" data-ride="carousel" style="margin-top: 16px;">
      <div class="carousel-inner" style="border-radius: 8px !important;">
        <%# -------- items --------- %>
        <div class="carousel-item active" data-interval="10000">
          <%= cl_image_tag @spot.default_image  %>
        </div>
        <% @posts.each do |post| %>
          <% imgs = PostContent.where(post_id: post.id) %>
          <% img_array = [] %>
          <% imgs.each do |img| %>
            <div class="carousel-item" data-interval="2000">
              <%= cl_image_tag img.media_url %>
            </div>
          <%end %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>



    <%# ---------map-------------- %>
    <div class="col-sm" style="padding: 0; border-radius: 8px !important; overflow-x: hidden !important; margin-top: 16px; width: 100%; min-height: 30vh; height: auto;"id="map" data-spot = "<%= @spot.to_json %>" data-view-type="spot" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>



<div class="container">
  <div style="margin-top: 16px; margin-left: 16 !important; width: 100%; box-shadow:3px 3px 5px 6px #ccc; border-radius: 10px; padding: 20px; background-color: white;">
    <%= simple_form_for :post, html: { multipart: true },  url: spot_posts_path(@spot.id) do |f| %>
      <%= simple_fields_for :no_model_fields do |n| %>
        <%= n.input :comment %>
        <%= n.file_field :pictures, multiple: true %>
      <% end %>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>

  <% @posts.each do |post| %>
    <% imgs = PostContent.where(post_id: post.id) %>
    <% img_array = [] %>
    <% imgs.each do |img| %>
      <% img_array << img %>
    <%end %>
    <% data_hash = {post: post, img: img_array, des: post.description}%>
    <%= render 'shared/moment-card', :data => data_hash%>
  <% end %>
</div>