config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post 'user_token' => 'user_token#create'
  devise_for :users
  root to: 'pages#home'

  # --- Create
  get '/spots/new', to: 'spots#new', as: :new_spot
  post '/spots', to: 'spots#create'

  # --- Read
  get '/spots', to: 'spots#index'
  get '/spots/:id', to: 'spots#show', as: :spot

  # --- Edit
  get '/spots/:id/edit', to: 'spots#edit', as: :edit_spot
  patch '/spots/:id', to: 'spots#update'

  # --- Delete
  delete '/spots/:id', to: 'spots#destroy', as: :destroy

  # --- Posts
  post '/spots/:spot_id/posts', to: 'posts#create', as: :spot_posts

  # --- Api
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :update, :create ] do
        collection do
          post 'favorites'
        end
        collection do
          get 'profile'
        end
      end
      resources :spots, only: [ :index, :show, :update, :create, :destroy ] do
        collection do
          get 'favorites'
        end
        resources :posts, only: [:index, :create]
      end
    end
  end

end

app/views/shared/_big-card.html.erb
<div class="card-product m-3" style="border-radius: 16px;">
<%= link_to spot do %>
     <div style="height: 200px; width: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path spot.default_image, :crop => :pad  %>');  background-position: center center; background-repeat: no-repeat; background-size: cover;">
    </div>
    <%end%>
    <div class="card-product-infos">
         <!-- <p>Address: <%= spot.geo_lat%> <%= spot.geo_lng%></p> -->
         <p>Address: <%= spot.address %></p>
         <p>Type: <%= spot.spot_type %></p>
         <p>Comments: <%= spot.posts.count %></p>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_moment-card.html.erb
<div class="card-product" style="border-radius: 16px; margin: 16px 0">
     <% if data[:img].first.nil? %>
     <% else %>
     <div style="height: 200px; width: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path data[:img].first.media_url, :crop => :pad  %>');  background-position: center center; background-repeat: no-repeat; background-size: cover;">
    </div>
     <%end%>

    <div class="card-product-infos">
        <p><%=data[:des]%></p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div style="height: 60px;" class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content-between align-items-center">
  <div class="d-flex justify-content-between align-items-center">
  <%= link_to "/", class: "navbar-brand" do %>
     <%= cl_image_tag 'https://res.cloudinary.com/doe2rb42f/image/upload/v1556116874/skateit-logo_pb3rke.png', width: 100 %>
    <% end %>
  </div>
  <div>
    <%= form_tag spots_path, method: :get do |f| %>
      <div class="search-form-control form-group m-3 d-flex align-items-center">
        <div class='add-skate-button'>
          <div >
            <%= link_to "/spots/new", class: "" do %>
              <i class="add-icon fas fa-plus" style="color:white;"></i>
            <% end %>
          </div>
        </div>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control string required search-form-control",
            placeholder: "Find a spot"
        %>
        <button name="button" type="submit" class="btn btn-flat">
          <i style="" class="search-icon fas fa-search"></i>
        </button>
      </div>
      <% end %>
    </div>
           <% if user_signed_in? %>
           <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
  </div>
</div>

app/views/shared/_skate-animation.html.erb
<div class="landscape">
  <div class="skate-container">
    <div class="skate">
      <div class="skate-board"></div>
      <div class="skate-wheels">
        <div></div>
        <div></div>
      </div>
    </div>
    <div class="skate-shadow"></div>
    <div class="skate-smoke">
      <div class="skate-smoke_item"></div>
      <div class="skate-smoke_item"></div>
      <div class="skate-smoke_item"></div>
    </div>
  </div>
  <div class="obstacles">
    <div class="obstacle_square"></div>
    <div class="obstacle_triangle"></div>
  </div>
</div>

app/views/shared/_small-card.html.erb
<%= link_to spot do %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path spot.default_image, height: 300, width: 300, crop: :fill %>'); background-position: center center; background-repeat: no-repeat; background-size: cover;">
    <i class="spot-icon fas fa-map-marker-alt"></i>
    <p class="spot-address"><%= spot.address %></p>
</div>
<%end%>

app/views/shared/_spot_card.html.erb
<% types = {
    0 => "Ledge",
    1 => "Rail",
    2 => "Stair set",
    3 => "Park",
    4 => "Transition",
    5 => "Manual pad"
}
%>

<div class="card-trip">
  <%= cl_image_tag spot.default_image, height: 100, width: 100, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2>Type: <%=types[spot.spot_type.to_i]%></h2>
      <p>Difficulty: <%= spot.difficulty_rating %></p>
    </div>
   <i class="fas fa-map-marker-alt"></i>
  </div>
</div>